# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f469eabc599b4c405b32af9ebb485be52ff7b015e24d04a444284966f2985ff12c4a1e66470e8461b34fa23a5e25c9f07f39e0572fb898c085b5805ada09697

test:
  secret_key_base: aa874ae34c21711b71b6377fb39a24c9b2255b0b87518abcbcae91d22ffd3cd8a5aef848e8dcf937d27f948a38d989358d8ce257d11a03a3f18fc04cc35dff3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
